# Generated by Django 5.2.5 on 2025-08-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderable_example', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['question']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='faqitem',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, editable=False, help_text='Ordering field for drag-and-drop functionality', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, editable=False, help_text='Ordering field for drag-and-drop functionality', null=True),
        ),
    ]
