# Generated by Django 5.2.5 on 2025-08-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderable_example', '0003_person_alter_faqitem_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('support', 'Support'), ('hr', 'HR')], default='engineering', max_length=100),
            preserve_default=False,
        ),
    ]
