# Generated by Django 5.2.5 on 2025-08-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_test_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqitem',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_order',
        ),
        migrations.AlterField(
            model_name='person',
            name='team',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('support', 'Support'), ('hr', 'HR')], max_length=50),
        ),
    ]
