# Generated by Django 5.2.5 on 2025-08-09 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_remove_faqitem_display_order_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FAQItem",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="photo",
        ),
    ]
